DROP INDEX VAH_index_donsmontos;
DROP INDEX VAH_index_regiones;
DROP INDEX VAH_index_ciudades;
DROP INDEX VAH_index_habs;
DROP INDEX VAH_index_eventos_anual;
DROP INDEX VAH_index_premios;
DROP INDEX VAH_index_personasnatu;
DROP INDEX VAH_index_personasjuri ;
DROP INDEX VAH_index_org_carna ;
DROP INDEX VAH_index_integrantes;
DROP INDEX VAH_index_titulos;
DROP INDEX VAH_index_hist_patros; 
DROP INDEX VAH_index_hist_intes ;
DROP TABLE VAH_estados CASCADE;
DROP TABLE VAH_ciudades CASCADE;
DROP TABLE VAH_escuelas CASCADE;
DROP TABLE VAH_hist_Titulos CASCADE;
DROP TABLE VAH_colores CASCADE;
DROP TABLE VAH_esc_Col CASCADE;
DROP TABLE VAH_sambas CASCADE;
DROP TABLE VAH_hist_Eventos_Anual_Sem CASCADE;
DROP TABLE VAH_personas_Juridicas CASCADE;
DROP TABLE VAH_personas_Naturales CASCADE;
DROP TABLE VAH_telefonos CASCADE;
DROP TABLE VAH_hist_Patrocinios CASCADE;
DROP TABLE VAH_donaciones CASCADE;
DROP TABLE VAH_integrantes CASCADE;
DROP TABLE VAH_hist_Integrantes CASCADE;
DROP TABLE VAH_autores CASCADE;
DROP TABLE VAH_roles CASCADE;
DROP TABLE VAH_org_Carnavales CASCADE;
DROP TABLE VAH_premios_Especiales CASCADE;
DROP TABLE VAH_ganadores CASCADE;
DROP TABLE VAH_parentescos CASCADE;
DROP TABLE VAH_habilidades CASCADE;
DROP TABLE VAH_int_Hab CASCADE;
DROP SEQUENCE VAH_sec_estados CASCADE;
DROP SEQUENCE VAH_sec_ciudades CASCADE;
DROP SEQUENCE vah_sec_escuelas CASCADE;
DROP SEQUENCE VAH_sec_colores CASCADE;
DROP SEQUENCE VAH_sec_sambas CASCADE;
DROP SEQUENCE VAH_sec_Eventos_Anual_Sem CASCADE;
DROP SEQUENCE VAH_sec_personas_Naturales CASCADE;
DROP SEQUENCE VAH_sec_personas_Juridicas CASCADE;
DROP SEQUENCE VAH_sec_hist_Patrocinios CASCADE;
DROP SEQUENCE VAH_sec_donaciones CASCADE;
DROP SEQUENCE VAH_sec_integrantes CASCADE;
DROP SEQUENCE VAH_sec_roles CASCADE;
DROP SEQUENCE VAH_sec_premios_Especiales CASCADE;
DROP SEQUENCE VAH_sec_habilidades CASCADE;